Editing system_test.yml

diff --git a/.github/workflows/system_test.yml b/.github/workflows/system_test.yml
--- a/.github/workflows/system_test.yml
+++ b/.github/workflows/system_test.yml
@@ -29,6 +29,23 @@ jobs:
           # and replace secrets.GITHUB_TOKEN with the secret in the fork
           echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
           bash .ci/system-tests/run_system_tests.sh ${GITHUB_REF#refs/heads/}
+      - name: Compose Down + Return exit code
+        shell: bash
+        run: |
+          # Clean up services and network
+          echo "*** Exiting and removing Docker containers and network ..."
+          docker compose -f ./.ci/docker/docker-compose-system-test.yml down -v
+
+          # Return container exit code
+          if [[ ${TEST_STATUS} == "0" ]]; then
+            echo "******** SUCCESS: System Tests for TPM 2.0 passed ********"
+            echo "TEST_STATUS=0" >> $GITHUB_ENV
+            exit 0;
+          else
+            echo "******** FAILURE: System Tests for TPM 2.0 failed ********"
+            echo "TEST_STATUS=1" >> $GITHUB_ENV
+            exit 1
+          fi
       - name: Archive System Test Log files
         uses: actions/upload-artifact@v4
         with:
